### ISSUE TITLE
Sprint 25 task list

### ISSUE THREAD

**Issue by DrUNE** [AdmiralDS/react-ui#1601]
- [ ] https://github.com/AdmiralDS/web-app-vite-admiral/issues/2
- [ ] Разработка курса по библиотеке
- [ ] Онбординг и прохождение обязательных курсов
